# This action builds an image and pushes it to Docker Hub on each commit to master
name: Push Latest to Docker Hub
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
            name: toniblyx/prowler
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            dockerfile: "./util/Dockerfile"
            tags: latest
