# This action builds an image and pushes it to Docker Hub when a new release is published
name: Push Release to Docker Hub
on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
            name: toniblyx/prowler
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            dockerfile: "./util/Dockerfile"
            tags: ${{ env.RELEASE_VERSION }}
